accounts/urls.py
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    # Account creation
    # /signup
    path('signup/', views.signup, name="signup")
]

urlpatterns += staticfiles_urlpatterns()

conlangdict/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('accounts.urls')),
    path('', include('dictionary.urls')),
]

dictionary/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'dictionary'

urlpatterns = [

    # choix du langage traduit et du langage de traduction
    # /dictionary/
    path('', views.IndexView.as_view(), name='index'),

    # renvoie à la liste des mots de la première initiale de <from_lang>
    # /search/<from_lang>/<to_lang>/
    # /search/HJP/FRA
    url(r'^search/(?P<natlang>\w+)/(?P<conlang>\w+)/*$',
        views.WordListView.as_view(),
        name='index_lang'),

    # renvoie à la liste des mots de la première initiale de <from_lang>
    # /search/<from_lang>/<to_lang>/<initial>
    # /search/HJP/FRA/a
    url(r'^search/(?P<natlang>\w+)/(?P<conlang>\w+)/(?P<initial>\w)/*$',
        views.InitialsListView.as_view(),
        name='index_initial'),

    # renvoie le détail de la traduction de `word` en `from_lang` vers
    # `to_lang`
    # /word/<from_lang>/<to_lang>/<slug>/
    # /word/HJP/FRA/hj-lp
    url(r'^word/(?P<from_lang>\w+)/(?P<to_lang>\w+)/(?P<slug>[-\w0-9]+)/*$',
        views.DetailView.as_view(),
        name='details'),

    # renvoie cinq mots de `from_lang` commençant par `word`
    # /guess/<from_lang>/<word>/
    # /guess/HJLP/hj
    url(r'^guess/(?P<from_lang>\w+)/(?P<word>[-\w0-9]+)/*$',
        views.guessword,
        name='guessword'),
]

dictionary/models.py
"""
Models for the database of the dictionary. This dictionary is thought of as a
bilingual dictionary capable of translating back and forth between natlangs
and the conlangs of https://langue.phundrak.fr
"""
from django.db import models
from django.utils.text import slugify


class Language(models.Model):
    """
    A general class to refer to languages, with its code and its name
    """
    code = models.CharField(max_length=8, primary_key=True)
    name = models.CharField(max_length=128)
    conlang = models.BooleanField(default=True)

    def __str__(self):
        return "{0.name} ({0.code})".format(self)

    class Meta:
        """
        Meta sub-class for ordering the languages
        """
        ordering = ('code', )


class Gender(models.Model):
    """
    Contains all possible gender in the languages supported by the
    dictionary, be it from natlangs or conlangs
    """
    code = models.CharField(max_length=8, primary_key=True)
    name = models.CharField(max_length=128)

    def __str__(self):
        return "{0.name} ({0.code})".format(self)

    class Meta:
        """
        Meta sub-class for ordering the genders
        """
        ordering = ('name', )


class Wordclass(models.Model):
    """Contains all the word classes available in the supported languages"""
    code = models.CharField(max_length=8, primary_key=True)
    name = models.CharField(max_length=64)

    def __str__(self):
        return "{0.name} ({0.code})".format(self)

    class Meta:
        """
        Meta sub-class for ordering the word classes
        """
        ordering = ('code', )


class Category(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

    def save(self, *arg, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(arg, kwargs)

    class Meta:
        ordering = ('name', )


class Word(models.Model):
    """
    Represents any word from any language. It has a self-representation with
    "word", a reference to which language it belongs to with "language", a list
    of words "translation" that can be its translation (duh), a reference to
    its gender with "gender" (duh2), its word class with "wordclass", some
    "details" about the word (no more than 5000 chars), its "etymology" (no
    more than 5000 chars) and a list of words that can be its etymological
    "roots"
    """
    word = models.CharField(max_length=128)
    slug = models.CharField(max_length=128, blank=True, editable=False)
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    translation = models.ManyToManyField("self", blank=True)
    gender = models.ForeignKey(Gender,
                               on_delete=models.SET_NULL,
                               null=True,
                               blank=True)
    wordclass = models.ManyToManyField(Wordclass, blank=True)
    category = models.ManyToManyField(Category, blank=True)
    roots = models.ManyToManyField("self", blank=True)
    details = models.TextField(max_length=8192, blank=True, null=True)
    etymology = models.TextField(max_length=8192, blank=True, null=True)

    def __str__(self):
        return self.word

    def save(self, *args, **kwargs):
        if self.word:
            self.slug = self.language.code + "-" + slugify(self.word)

        super(Word, self).save(args, kwargs)

    class Meta:
        """
        Meta sub-class for ordering words
        """
        ordering = ('slug', )

dictionary/forms.py
"""
Forms that will be used for various user actions, such as language selection on
the main page, user registration or authentification.
"""
from django import forms
from django.contrib.auth.models import User
from .models import Language


class SelectLangForm(forms.Form):
    natlang = forms.ModelChoiceField(
        queryset=Language.objects.all(),
        label="Natural Language:",
        to_field_name="code")
    conlang = forms.ModelChoiceField(
        queryset=Language.objects.all(),
        label="Constructed Language:",
        to_field_name="code")


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

dictionary/views.py
"""
Views for the dictionary
"""

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import DetailView, ListView, View

# from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import SelectLangForm
from .models import Language, Word


class IndexView(View):
    """
    View for the main page. Two drop-down boxes will give the choice between
    which languages to translate, one will be used to select a natural language,
    the other a conlang.

    View for /
    """
    form_class = SelectLangForm
    template_name = 'dictionary/index.html'
    error_message = ""

    def get(self, request):
        """
        Displays the index page
        """
        form = self.form_class(None)
        return render(
            request, self.template_name, {
                'form': form,
                'conlangs': Language.objects.filter(conlang=True),
                'natlangs': Language.objects.filter(conlang=False),
                'error_message': self.error_message
            })

    def post(self, request):
        """
        Processes the form and redirects to the correct bilingual word list page
        if the form is correct, or to the main page if not
        """
        form = self.form_class(request.POST)
        if form.is_valid():
            natlang = form.cleaned_data['natlang']
            conlang = form.cleaned_data['conlang']
            return HttpResponseRedirect('/search/' + natlang.code + '/' +
                                        conlang.code)
        print(form.errors)
        self.error_message = form.errors
        return render(
            request, self.template_name, {
                'form': form,
                'conlangs': Language.objects.filter(conlang=True),
                'natlangs': Language.objects.filter(conlang=False),
                'error_message': self.error_message,
            })


class WordListView(ListView):
    """
    Will list all the words from the language `natlang` translated to the
    language `conlang` and vice-versa

    View for /search/from_lang/to_lang
    """

    template_name = 'dictionary/language.html'
    context_object_name = 'natwords'
    form_class = SelectLangForm
    error_message = ""

    def get_queryset(self):
        """
        Get initial values to display
        """
        return Word.objects.filter(
            language__code=self.kwargs['natlang'],
            translation__language__code=self.kwargs['conlang']).distinct()

    def get_context_data(self, **kwargs):
        """
        Get some additional values
        """
        context = super(WordListView, self).get_context_data(**kwargs)
        context['conwords'] = Word.objects.filter(
            language__code=self.kwargs['conlang'],
            translation__language__code=self.kwargs['natlang']).distinct()
        context['natlang'] = Language.objects.filter(conlang=False)
        context['conlang'] = Language.objects.filter(conlang=True)
        context['cur_natlang'] = Language.objects.get(
            code=self.kwargs['natlang'])
        context['cur_conlang'] = Language.objects.get(
            code=self.kwargs['conlang'])
        return context


class InitialsListView(ListView):
    """
    Displays all the words from both languages beginning with a specified
    initial letter
    """

    # TODO: create dedicated template
    template_name = 'dictionary/language.html'
    context_object_name = 'natwords'

    def get_queryset(self):
        """
        Get initial values to display
        """
        return Word.objects.filter(
            language__code=self.kwargs['natlang'],
            slug__startswith=self.kwargs['initial'],
            translation__language__code=self.kwargs['conlang'])

    def get_context_data(self, **kwargs):
        """
        Get some additional values
        """
        context = super(InitialsListView, self).get_context_data(**kwargs)
        context['conwords'] = Word.objects.filter(
            language__code=self.kwargs['conlang'],
            slug__startswith=self.kwargs['initial'],
            translation__language__code=self.kwargs['natlang'])
        context['natlang'] = Language.objects.get(code=self.kwargs['natlang'])
        context['conlang'] = Language.objects.get(code=self.kwargs['conlang'])
        return context


class DetailView(DetailView):
    """
    Displays the details about the word `word` from the language `from_lang` if
    this word is from a conlang and will display its translations to the
    language `to_lang`

    View for /word/from_lang/to_lang/slug
    """
    model = Word
    template_name = 'dictionary/details.html'
    context_object_name = 'word'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['translations'] = context['word'].translation.filter(
            language=self.kwargs['to_lang'])
        context['from_lang'] = Language.objects.get(
            code=self.kwargs['from_lang'])
        context['to_lang'] = Language.objects.get(code=self.kwargs['to_lang'])
        return context


def guessword(request, from_lang, word):
    """
    Is used to get five words from `from_lang` beginning with `word`. This will
    be used for word suggestion when using the search bar.

    View for /guess/from_lang/word
    """
    pass

dictionary/templates/dictionary/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'dictionary/css/style.css' %}" type="text/css" media="screen" />
    <link rel="shortcut icon" href="https://cdn.phundrak.fr/img/mahakala-128x128.png" type="image/png" media="screen" />
    <link rel="shortcut icon" href="https://cdn.phundrak.fr/img/mahakala-128x128.png" type="image/png" />
    <script type="text/javascript" src="{% static 'dictionary/js/animations.js' %}"></script>
    <meta property="og:image" content="https://cdn.phundrak.fr/img/rich_preview.jpg" />
    <meta property="og:title" content="Dictionnaire de Conlangs" />
    <meta property="og:description" content="Dictionnaire bilingue en ligne des langues construites de P’undrak" />
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@phundrak" />
    <meta name="twitter:creator" content="@phundrak" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block addhead %}{% endblock %}
</head>

<body>
    {% include 'dictionary/ribbon.html' %}
    <div class="content" onscroll="hideRibbon()">
        <div class="errormessage">
            {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
            {% endif %}
        </div>
        {% block body %}
        {% endblock %}
    </div>
</body>

</html>

dictionary/templates/dictionary/details.html
{% extends 'dictionary/base.html' %}
{% load static %}

<!--
     Requires:
     `word` is the main word of the page, Word
     `translations` are all the words that translate `word` to other languages, Word[]
     `from_lang` is the original language, Language
     `to_lang` is the target language, Language
-->

<!-- TITLE ------------------------------------------------------------------->
{% block title %}{{ word.word }} - {{ from_lang.name }}{% endblock %}

<!-- HEADER ------------------------------------------------------------------>
{% block addhead %}
<link rel="stylesheet" href="{% static 'dictionary/css/details.css' %}" type="text/css" media="screen" />
{% endblock %}

<!-- SIDEBAR ----------------------------------------------------------------->
{% block sidebarcontent %}
<h1 class="sidebar-title">Detailed Translation</h1>
{% include "dictionary/footer-back-index.html" %}
{% endblock %}

<!-- BODY -------------------------------------------------------------------->
{% block body %}
<div class="wordcard">
    <div class="word">{{ word.word }}</div>
    <div class="fromlang">
        <p class="title">Language: </p>
        <p>{{ from_lang.name }}</p>
    </div>
    <div class="gender">
        {% if word.gender %}
        <p class="title">Gender:</p>
        <p>{{ word.gender }}</p>
        {% endif %}
    </div>
    <div class="wordclass">
        <p class="title">Word class:</p>
        <p>{% for wclass in word.wordclass.all %}{{wclass}}{% endfor %}</p>
    </div>
    <div class="listtrans">
        {% if translations %}
        <p class="title">Translations of “{{ word.word }}” in {{ to_lang.name }}:</p>
        {% for translation in translations %}
        <a href="{% url 'dictionary:details' to_lang.code from_lang.code translation.slug %}">
            <p class="card">{{ translation.word }}: {% for twclass in translation.wordclass.all %}{{twclass}} {% endfor %}</p>
        </a>
        {% endfor %}
        {% endif %}
    </div>
    <div class="transdetails">
        {% if word.details %}
        <p class="title">Details:</p>
        <p>{{ word.details }}</p>
        {% endif %}
    </div>
    <div class="etymology">
        {% if word.etymology %}
        <p class="title">Etymology: </p>
        <p>{{word.etymology}}</p>
        {% endif %}
        {% if word.roots.all %}
        <div class="roots">
            <p class="title">Etymological roots:</p>
            {% for root in word.roots.all %}
            <a href="{% url 'dictionary:details' from_lang.code to_lang.code root.slug %}">
                <p class="card">{{root.word}} ({{root.wordclass.name}})</p>
            </a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

dictionary/templates/dictionary/form_template.html
{% for field in form %}
<span class="text-danger small">{{field.errors}}</span>
<label class="control-lablel">{{field.label_tag}}</label>
<div>{{field}}</div>
{% endfor %}

dictionary/templates/dictionary/index.html
<!--
     Requires:
     `natlangs` List of Language objects
     `conlangs` List of Language objects
-->

{% extends 'dictionary/base.html' %}
{% load static %}

<!---------------------------------------------------------------------------->
<!--               Page d’accueil, sélection des deux langues               -->
<!---------------------------------------------------------------------------->

{% block title %}Language selection{% endblock %}

{% block addhead %}
<link rel="stylesheet" href="{% static 'dictionary/css/index.css' %}" type="text/css" media="screen" />
{% endblock %}

{% block body %}
<h1 class="index-title">Welcome to Phundrak’s ConlangDict!</h1>
{% endblock %}

dictionary/templates/dictionary/language.html
<!--
     Requires:
     `natwords` List of Word objects
     `conwords` List of Word objects
     `cur_natlang` Language object
     `cur_conlang` Language object
-->

{% extends 'dictionary/base.html' %}
{% load static %}

<!-- TITLE ------------------------------------------------------------------->
{% block title %}{{cur_natlang.name}} ⇌ {{cur_conlang.name}}{% endblock %}

<!-- HEADERS ----------------------------------------------------------------->
{% block addhead %}
<link rel="stylesheet" href="{% static 'dictionary/css/language.css' %}" type="text/css" media="screen" />
{% endblock %}

<!-- SIDEBAR ----------------------------------------------------------------->
{% block sidebarcontent %}
<h1 class="sidebar-title">Translating between {{cur_natlang.name}} and {{cur_conlang.name}}</h1>
{% include "dictionary/footer-back-index.html" %}
{% endblock %}

<!-- BODY -------------------------------------------------------------------->
{% block body %}
<div class="natlangw">
    <h2>{{cur_natlang.name}}</h2>
    <div class="wordlist">
        {% for word in natwords %}
        <a href="{% url 'dictionary:details' cur_natlang.code cur_conlang.code word.slug %}" class="wordblock">
            <div class="word">{{word.word}}</div>
            <div class="wclass">
                {% if word.wordclass %}
                {% for wclass in word.wordclass.all %}
                {{wclass}}
                {% endfor %}
                {% endif %}
            </div>
            <div class="gender">{% if word.gender %}{{word.gender}}{% endif %}</div>
            <ul class="translations">
                {% for trans in word.translation.all %}
                {% if trans.language.code == cur_conlang.code %}
                <li>{{trans}}</li>
                {% endif %}
                {% endfor %}
            </ul>
        </a>
        {% endfor %}
    </div>
</div>
<div class="conlangw">
    <h2>{{cur_conlang.name}}</h2>
    <div class="wordlist">
        {% for word in conwords %}
        <a href="{% url 'dictionary:details' cur_conlang.code cur_natlang.code word.slug %}" class="wordblock">
            <div class="word">{{word.word}}</div>
            <div class="wclass">
                {% if word.wordclass %}
                {% for wclass in word.wordclass.all %}
                {{wclass}}
                {% endfor %}
                {% endif %}
            </div>
            <div class="gender">{% if word.gender %}{{word.gender}}{% endif %}</div>
            <ul class="translations">
                {% for trans in word.translation.all %}
                {% if trans.language.code == cur_natlang.code %}
                <li>{{trans}}</li>
                {% endif %}
                {% endfor %}
            </ul>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

dictionary/templates/dictionary/registration_form.html
{% extends 'dictionary/base.html' %}
{% load static %}

<!---------------------------------------------------------------------------->
<!--                            Registration page                           -->
<!---------------------------------------------------------------------------->


<!-- title ------------------------------------------------------------------->
{% block title %}Account Registration{% endblock %}

<!-- headers ----------------------------------------------------------------->
{% block addhead %}
<link rel="stylesheet" href="{% static 'dictionary/css/registration.css' %}" type="text/css" media="screen" />
{% endblock %}

<!-- sidebar ----------------------------------------------------------------->
{% block sidebarcontent %}
{% endblock %}

<!-- body -------------------------------------------------------------------->
{% block body %}
<h3>Register a new account</h3>
<form method="post" action="">
    {% csrf_token %}
    {% include 'dictionary/form_template.html' %}
    <button type="submit">Submit</button>
</form>
{% endblock %}

dictionary/templates/dictionary/ribbon.html
<!--
     Requires:
     `natlang` Language object
     `conlang` Language object
-->
<div class="ribbon">
    <div class="ribbon-nav">
        <h2><a class="ribbon-link" href="{% url 'dictionary:index' %}">Home</a></h2>
    </div>
    <form id="language-select" method="post" action="/" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="sourcelang">
            <label for="source"></label>
            <div class="form-style">
                <select id="source" name="natlang">
                    {% for lang in natlangs %}
                    <option value="{{lang.code}}">{{lang.name}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="destlang">
            <label for="dest">and</label>
            <div class="form-style">
                <select id="dest" name="conlang">
                    {% for lang in conlangs %}
                    <option value="{{lang.code}}">{{lang.name}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <submit class="form-style">
            <input type="submit" value="Let’s Go!">
        </submit>
    </form>
    <div class="ribbon-searchbar">

    </div>
    <div class="ribbon-user-account">
        {% if user.is_authentificated %}
        <h2><a class="ribbon-link" href="#logout">Logout</a></h2>
        {% else %}
        <h2><a class="ribbon-link" href="#login">Login</a></h2>
        {% endif %}
    </div>
</div>